<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Compliance Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f5f5f5;
        }

        .header {
            margin-bottom: 20px;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Compliance Report</h1>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    @if ($content->isEmpty())
        <p>No data available for the selected criteria.</p>
    @else
        <table>
            <thead>
                <tr>
                    @foreach (array_keys($content->first()->toArray()) as $header)
                        <th>{{ ucwords(str_replace('_', ' ', $header)) }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($content as $row)
                    <tr>
                        @foreach ($row->toArray() as $value)
                            <td>{{ is_array($value) || is_object($value) ? json_encode($value) : $value }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>Generated by {{ config('app.name') }} - Page {PAGE_NUM} of {PAGE_COUNT}</p>
    </div>
</body>

</html>
