<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Campaign extends Model
{
  use HasFactory;

  /**
   * The attributes that are mass assignable.
   *
   * @var array<int, string>
   */
  protected $fillable = [
    'name',
    'type',
    'start_date',
    'end_date',
    'budget',
    'target_audience',
    'goals',
    'description',
    'status',
    'created_by'
  ];

  /**
   * The attributes that should be cast.
   *
   * @var array<string, string>
   */
  protected $casts = [
    'start_date' => 'date',
    'end_date' => 'date',
    'budget' => 'decimal:2',
    'target_audience' => 'array',
    'goals' => 'array'
  ];

  /**
   * Get the leads generated by this campaign.
   */
  public function leads()
  {
    return $this->hasMany(Lead::class);
  }

  /**
   * Get the opportunities generated by this campaign.
   */
  public function opportunities()
  {
    return $this->hasMany(Opportunity::class);
  }

  /**
   * Get the email campaigns associated with this campaign.
   */
  public function emailCampaigns()
  {
    return $this->hasMany(EmailCampaign::class);
  }

  /**
   * Get the social media posts associated with this campaign.
   */
  public function socialMediaPosts()
  {
    return $this->hasMany(SocialMediaPost::class);
  }

  /**
   * Get the analytics for this campaign.
   */
  public function analytics()
  {
    return $this->hasOne(MarketingAnalytics::class);
  }

  /**
   * Get the user who created the campaign.
   */
  public function creator()
  {
    return $this->belongsTo(User::class, 'created_by');
  }

  /**
   * Get all of the campaign's notes.
   */
  public function notes()
  {
    return $this->morphMany(Note::class, 'notable');
  }

  /**
   * Get all of the campaign's activities.
   */
  public function activities()
  {
    return $this->morphMany(Activity::class, 'activitable');
  }
}
