@extends('layouts/contentNavbarLayout')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Budget Reports</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                data-target="#generateReportModal">
                                Generate Report
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Report Name</th>
                                        <th>Type</th>
                                        <th>Format</th>
                                        <th>Generated By</th>
                                        <th>Date</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($reports as $report)
                                        <tr>
                                            <td>{{ $report->name }}</td>
                                            <td>{{ ucfirst($report->type) }}</td>
                                            <td>{{ strtoupper($report->format) }}</td>
                                            <td>{{ $report->creator->name }}</td>
                                            <td>{{ $report->created_at->format('Y-m-d H:i') }}</td>
                                            <td>
                                                <a href="{{ route('budgets.reports.generate', ['id' => $report->id]) }}"
                                                    class="btn btn-sm btn-info">
                                                    Download
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Generate Report Modal -->
    <div class="modal fade" id="generateReportModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="{{ route('budgets.reports.generate') }}" method="GET">
                    <div class="modal-header">
                        <h5 class="modal-title">Generate Budget Report</h5>
                        <button type="button" class="close" data-dismiss="modal">
                            <span>&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Report Type</label>
                            <select name="type" class="form-control" required>
                                <option value="department">Department</option>
                                <option value="project">Project</option>
                                <option value="cost_category">Cost Category</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Format</label>
                            <select name="format" class="form-control" required>
                                <option value="pdf">PDF</option>
                                <option value="excel">Excel</option>
                            </select>
                        </div>
                        <div class="form-group parameters-department" style="display: none;">
                            <label>Department</label>
                            <select name="parameters[department_id]" class="form-control">
                                @foreach (App\Models\Department::all() as $department)
                                    <option value="{{ $department->id }}">{{ $department->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group parameters-project" style="display: none;">
                            <label>Project</label>
                            <select name="parameters[project_id]" class="form-control">
                                @foreach (App\Models\Project::all() as $project)
                                    <option value="{{ $project->id }}">{{ $project->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group parameters-cost_category" style="display: none;">
                            <label>Cost Category</label>
                            <select name="parameters[cost_category_id]" class="form-control">
                                @foreach (App\Models\CostCategory::all() as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Generate</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            document.querySelector('select[name="type"]').addEventListener('change', function() {
                document.querySelectorAll('[class^="parameters-"]').forEach(el => el.style.display = 'none');
                document.querySelector('.parameters-' + this.value).style.display = 'block';
            });
        </script>
    @endpush
@endsection
